# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7a24815a2f275e47e18f1244d658b769af3101c9d59df65260bef5c59f44c875fc0f69f3f514aa962ab42e45ae5fc2b4a5fa7bca129624dd90ca80a85fa613bf

test:
  secret_key_base: 71b5497d7d856660c53edfdab14c6e46e51188dd961aa1b95f7460b1a3c6f54c43c2e9a06423497b31b4806c673a56b3f0485e09c9abd09a76e41f66f57d0a3b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
